version: '3.9'

services:

  mvc:
    build:
      context: .
      dockerfile: ./StrengthJournal.MVC/StrengthJournal.MVC/Dockerfile
    env_file:
      - dotnet.env

  gateway:
    build:
      context: .
      dockerfile: ./sj-server-nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"