name: Build containers and deploy to container apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'services/**'
    - '.github/workflows/main_StrengthJournal.yml'
    - '**/*.bicep'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: strengthjournalservices.azurecr.io
          username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

      - name: Add version tag to SPA
        working-directory: ./services/sj-app-angular
        run: sed -i "s/{REVISION_HASH}/${{ github.sha }}/" ./src/environments/environment.prod.ts

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: strengthjournalservices.azurecr.io/server:${{ github.sha }}
          file: ./services/sj-server-nginx/Dockerfile
          context: ./services

  build-iam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: strengthjournalservices.azurecr.io
          username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: strengthjournalservices.azurecr.io/iam:${{ github.sha }}
          file: ./services/StrengthJournal.IAM/StrengthJournal.IAM.API/Dockerfile
          context: ./services

  build-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: strengthjournalservices.azurecr.io
          username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: strengthjournalservices.azurecr.io/journal:${{ github.sha }}
          file: ./services/StrengthJournal.Journal/StrengthJournal.Journal.API/Dockerfile
          context: ./services

  build-mvc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: strengthjournalservices.azurecr.io
          username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: strengthjournalservices.azurecr.io/mvc:${{ github.sha }}
          file: ./services/StrengthJournal.MVC/StrengthJournal.MVC/Dockerfile
          context: ./services

  deploy-test-environment:
    environment: strengthjournal-test-arch2
    name: TEST Deploy app service Azure infrastructure
    runs-on: ubuntu-latest
    needs:
    - build-server
    - build-iam
    - build-journal
    - build-mvc
    env:
      AZURE_RESOURCEGROUP_NAME: strengthjournal-test-arch2
      DOTNET_ENV: test
      AZURE_TENANT_ID: 31e50e54-3b13-47ed-938e-8600cb767ae7
      AZURE_CLIENT_ID: f15b8bb4-c5b6-410f-b185-ca5c4c5619cc
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./environment-arch2.bicep
        parameters: containerDeploymentRevision=${{ github.sha }} dotnetEnv=${{ env.DOTNET_ENV }} dotnetAzTenantId=${{ env.AZURE_TENANT_ID }} dotnetAzClientId=${{ env.AZURE_CLIENT_ID }} dotnetAzClientSecret=${{ secrets.AZURE_CLIENT_SECRET }}

  deploy-production-environment-blue:
    environment: strengthjournal-prod-arch2-blue
    name: PRODBLUE Deploy app service Azure infrastructure
    runs-on: ubuntu-latest
    needs:
    - build-server
    - build-iam
    - build-journal
    - build-mvc
    env:
      AZURE_RESOURCEGROUP_NAME: strengthjournal-prod-arch2-blue
      DOTNET_ENV: prod
      AZURE_TENANT_ID: 31e50e54-3b13-47ed-938e-8600cb767ae7
      AZURE_CLIENT_ID: bd192fd3-3e31-4cd9-82ed-02f5db019ddf
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./environment-arch2.bicep
        parameters: containerDeploymentRevision=${{ github.sha }} dotnetEnv=${{ env.DOTNET_ENV }} dotnetAzTenantId=${{ env.AZURE_TENANT_ID }} dotnetAzClientId=${{ env.AZURE_CLIENT_ID }} dotnetAzClientSecret=${{ secrets.AZURE_CLIENT_SECRET }}