name: Build containers and deploy to container apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'services/**'
    - '.github/workflows/main_StrengthJournal.yml'
    - '**/*.bicep'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  deploy-test-environment:
    environment: strengthjournal-test-arch1
    name: Deploy app service Azure infrastructure
    runs-on: ubuntu-latest
    env:
      AZURE_RESOURCEGROUP_NAME: strengthjournal-test-arch2
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./environment-arch2.bicep

  # build-server:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout to the branch
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to container registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: strengthjournalservices.azurecr.io
  #         username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
  #         password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

  #     - name: Build and push container image to registry
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: strengthjournalservices.azurecr.io/server:${{ github.sha }}
  #         file: ./services/sj-server-nginx/Dockerfile
  #         context: ./services

  # build-iam:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout to the branch
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to container registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: strengthjournalservices.azurecr.io
  #         username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
  #         password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

  #     - name: Build and push container image to registry
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: strengthjournalservices.azurecr.io/iam:${{ github.sha }}
  #         file: ./services/StrengthJournal.IAM/StrengthJournal.IAM.API/Dockerfile
  #         context: ./services

  # build-journal:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout to the branch
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to container registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: strengthjournalservices.azurecr.io
  #         username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
  #         password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

  #     - name: Build and push container image to registry
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: strengthjournalservices.azurecr.io/journal:${{ github.sha }}
  #         file: ./services/StrengthJournal.Journal/StrengthJournal.Journal.API/Dockerfile
  #         context: ./services

  # build-mvc:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout to the branch
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to container registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: strengthjournalservices.azurecr.io
  #         username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
  #         password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

  #     - name: Build and push container image to registry
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: strengthjournalservices.azurecr.io/mvc:${{ github.sha }}
  #         file: ./services/StrengthJournal.MVC/StrengthJournal.MVC/Dockerfile
  #         context: ./services

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #   - build-server 
  #   - build-iam 
  #   - build-journal 
  #   - build-mvc
    
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS_TEST_ARCH1 }}

  #     - name: Deploy to containerapp
  #       uses: azure/CLI@v1
  #       with:
  #         inlineScript: |
  #           az config set extension.use_dynamic_install=yes_without_prompt
  #           az containerapp update -n iam -g strengthjournal-test-arch1 --image strengthjournalservices.azurecr.io/iam:${{ github.sha }}
  #           az containerapp update -n journal -g strengthjournal-test-arch1 --image strengthjournalservices.azurecr.io/journal:${{ github.sha }}
  #           az containerapp update -n mvc -g strengthjournal-test-arch1 --image strengthjournalservices.azurecr.io/mvc:${{ github.sha }}
  #           az containerapp update -n gateway -g strengthjournal-test-arch1 --image strengthjournalservices.azurecr.io/server:${{ github.sha }}