name: Build containers and deploy to container apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'sj-server-nginx/**'
    - '.github/workflows/main_StrengthJournal.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: strengthjournalservices.azurecr.io
          username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: strengthjournalservices.azurecr.io/server:${{ github.sha }}
          file: ./services/sj-server-nginx/Dockerfile
          context: ./services


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.GATEWAY_AZURE_CREDENTIALS }}


  #     - name: Deploy to containerapp
  #       uses: azure/CLI@v1
  #       with:
  #         inlineScript: |
  #           az config set extension.use_dynamic_install=yes_without_prompt
  #           az containerapp registry set -n gateway -g DefaultResourceGroup-CCAN --server strengthjournalservices.azurecr.io --username  ${{ secrets.GATEWAY_REGISTRY_USERNAME }} --password ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}
  #           az containerapp update -n gateway -g DefaultResourceGroup-CCAN --image strengthjournalservices.azurecr.io/gateway:${{ github.sha }}
