# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - StrengthJournal-Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: Inject build commit SHA
        working-directory: ./strengthjournal-app
        run: |
            npm install
            node .\inject-build-metadata.js -r '${{github.sha}}'
          
      - name: Build SPA
        working-directory: ./strengthjournal-app
        run: npm run build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./strengthjournal-server
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./strengthjournal-server
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/server-and-spa

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: 'server-and-spa'
          path: ${{env.DOTNET_ROOT}}/server-and-spa

  deploy-test:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: 'server-and-spa'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StrengthJournal-Test'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e64a5527a63e4237a884044ddfdba221 }}
          package: .


  deploy-prod:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: 'server-and-spa'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StrengthJournal-Prod'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: .